# Preface to the {{< var ay >>}} presentation {.unnumbered}

Welcome to the {{< var ay >>}} edition of the statistics supporting information for the BM110 microbiology laboratory.

We would be very grateful to hear feedback about this workshop material [by email]({{< var admin.email >}}) or through the [GitHub repository Issues page]({{< var github.issues >}}).

## Overview

These pages provide support and background to the statistical calculations you will be using in the BM110 microbiology laboratories.

The practical work aims to determine whether antimicrobial use in factory farming might contribute to spillover of antimicrobial resistance genes in the environment.

To test this hypothesis (that antimicrobial use on a farm results in greater occurrence of antimicrobial-resistant bacteria), a number of soil samples have been collected from two different farms, A and B. These two farms have differing practices, most specifically concerning their prophylactic use of antimicrobials.

In the laboratory, you plated out (collectively) two serial dilutions ($10^{-1}$ and $10^{-2}$) of bacteria from two farm soil samples, and observed the number of colonies on each plate to obtain (again collectively) colony-forming unit (CFU) measurements for each of four conditions:

1. Farm A, nutrient agar (NA)
2. Farm A, nutrient agar + Ampicillin (Amp)
3. Farm B, nutrient agar (NA)
4. Farm B, nutrient agar + Ampicillin (Amp)